# Generated by Django 4.1.5 on 2023-02-21 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_shop_notification_dtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_notification',
            name='dtime',
        ),
        migrations.AddField(
            model_name='shop_notification',
            name='Datetimeshop',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
